--- #YAML:1.0
name:                Getopt-Lazy
version:             v0.0.5
abstract:            Yet another lazy, minimal way of using Getopt::Long
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    File::Basename:                1
    Test::More:                    0
    Text::Wrap:                    1
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ruey-Cheng Chen <rueycheng@gmail.com>
